#!/usr/bin/env python3
"""Saigon → Da Lat → Mui Ne, 8-13 September 2026.

Six days, five nights: two in Saigon, two in Da Lat, one in Mui Ne. Non-halal
cafés and restaurants stay off the list; every meal is a halal address, and in
Saigon the hotel sits by the Central Mosque on Đông Du street.

Run:    python3 dalat-muine-saigon/build_trip_pdf.py
Output: dalat-muine-saigon/Itinerary-Saigon-DaLat-MuiNe.html  +  .pdf
"""

import os
import sys

sys.path.insert(0, os.path.join(os.path.dirname(os.path.abspath(__file__)), ".."))
from trips import itinerary_pdf as engine  # noqa: E402

OUT_DIR = os.path.dirname(os.path.abspath(__file__))
GUESTS = "Haris Haikal &amp; Aina Izzaty"
H_SGN = "Alagon Saigon Hotel &amp; Spa (4★)"
H_DL = "Hôtel Colline Dalat (4★)"
H_MN = "Bamboo Village Beach Resort &amp; Spa (4★)"

DAYS = [
    dict(
        n="DAY 1", date="Tuesday, 8 September", title="Fly to Saigon — the walking street at dusk",
        color="#46688C",
        outfit="<b>Soft blue + brown</b> — café theme for the first evening",
        start="Morning MAS from KLIA", finish="~21.30", sleep=f"{H_SGN} — nights 1–2",
        rows=[
            ("stop", "morning", "KUL → SGN — Malaysia Airlines", "KLIA", "~2h",
             "MH750 / MH758 / MH766, about 7 a day. Take one landing early afternoon. Vietnam is <b>1 hour behind Malaysia</b>."),
            ("move", "Tan Son Nhat &rarr; District 1 &mdash; 8 km, 30&ndash;45 min in traffic", "", "", "", ""),
            ("stop", "~14.30", f"Check in — <b>{H_SGN}</b>",
             "District 1, by Đông Du street", "1h",
             "Check-in 14:00, checkout 12:00. Chosen for position: the <b>Saigon Central Mosque is on Đông Du</b>, and a dozen halal restaurants sit within a five-minute walk."),
            ("stop", "~16.00", "Nguyễn Huệ walking street", "District 1", "1h",
             "The wide pedestrian boulevard up to the old City Hall. Ten minutes on foot from the hotel."),
            ("stop", "~17.15", "The Café Apartment, 42 Nguyễn Huệ", "Nguyễn Huệ", "1.5h",
             "A nine-storey 1960s block where every flat is a café or tiny shop, each with a balcony over the street. Ride the lift to the top and walk down. <b>Photos and the view</b> — eat at Đông Du."),
            ("stop", "~19.00", "🍽 Dinner — Đông Du street", "District 1, by the mosque", "1.5h",
             "Several halal restaurants in one short street, all a few minutes from the hotel. This is the easiest eating of the whole trip — make the most of it."),
            ("stop", "~20.45", "Bùi Viện or a rooftop", "District 1", "1h",
             "Optional. Saigon does rooftops well; the ones over Nguyễn Huệ have the best view down the boulevard."),
        ],
        notes=[
            "Easy first day by design — one flight, no connection, no long transfer.",
            "Saigon in September is hot, humid and has a heavy shower most afternoons that clears in an hour. Nothing today minds rain.",
            "<b>Book the 10 Sept Da Lat flight now if you haven't</b> — six a day, 55 minutes, and you want a 07:00–09:00 departure.",
        ],
    ),
    dict(
        n="DAY 2", date="Wednesday, 9 September", title="Saigon — the colonial quarter and the market",
        color="#A8763A",
        outfit="<b>Cream fairytale</b> — the post office and Đồng Khởi are built for it",
        start="08.30", finish="~21.00", sleep=f"{H_SGN} — night 2",
        rows=[
            ("stop", "08.30", "🍽 Breakfast at the hotel", f"{H_SGN}", "1h", "Included. Then straight out — mornings are the cool half of a Saigon day."),
            ("stop", "~09.45", "Saigon Central Post Office", "Công xã Paris, District 1", "1h",
             "Gustave Eiffel-era ironwork, painted tiles, and still a working post office — send yourselves a postcard from the counter. The cream-outfit location."),
            ("stop", "~11.00", "Book Street (Đường Sách) + Đồng Khởi", "District 1", "1.25h",
             "A shaded lane of bookshops beside the post office, then the old French shopping street down toward the river."),
            ("stop", "~12.30", "🍽 Lunch — Đông Du street", "District 1", "1.25h",
             "Back to the halal street. It's five minutes from Đồng Khởi, so this costs you nothing."),
            ("stop", "~14.00", "Bến Thành Market + Saigon Square", "District 1", "2h",
             "Bến Thành for souvenirs and dried fruit, Saigon Square for clothes and bags. Bargain hard — open at about 40% of the asking price."),
            ("stop", "~16.15", "Bitexco Saigon Skydeck", "Hải Triều, District 1", "1.25h",
             "The 49th-floor deck for the whole city and the river bend. Go late afternoon and stay through the light changing."),
            ("stop", "~18.00", "Back to the hotel — rest and repack", f"{H_SGN}", "1h",
             "You fly to Da Lat in the morning. Repack so the Da Lat bag is the small one."),
            ("stop", "~19.15", "🍽 Dinner — Đông Du street", "District 1", "1.5h",
             "Different restaurant, same street. Then early night — tomorrow is a flight."),
        ],
        notes=[
            "Everything today is inside District 1 and walkable, or a 5-minute Grab. No car needed.",
            "<b>Prefer countryside?</b> Swap today for a Mekong Delta day trip (My Tho or Ben Tre, ~2h each way) — but arrange halal food yourself, because tour lunches are not. See the spare page.",
            "If the afternoon storm lands, Bến Thành and the Skydeck are both indoors. Save the post office for the clear hour.",
        ],
    ),
    dict(
        n="DAY 3", date="Thursday, 10 September", title="Up to Da Lat — Tà Nung, then the lake",
        color="#6B6A52",
        outfit="<b>Khaki + black</b> — travel morning, and it suits the steppe at Mongo Land",
        start="06.30", finish="~21.00", sleep=f"{H_DL} — nights 3–4",
        compact=True,
        rows=[
            ("stop", "06.30", f"Checkout — <b>{H_SGN}</b>", "District 1", "30 min", "Checkout is 12:00, but the flight is early. Breakfast boxed if they'll do it."),
            ("stop", "~08.00", "SGN → DLI — Vietnam Airlines or Vietjet", "Tan Son Nhat T1", "55 min",
             "Six a day. A 07:00–09:00 departure gets you into Da Lat with the whole afternoon intact. Domestic terminal, so no immigration."),
            ("move", "Lien Khuong airport &rarr; Da Lat city &mdash; 30 km, ~40 min", "", "", "", ""),
            ("stop", "~10.30", f"Check in — <b>{H_DL}</b>",
             "10 Phan Bội Châu, city centre", "45 min",
             "Check-in 14:00, but they'll hold bags — drop and go. 200 m from Xuan Huong Lake, and walkable to both of Da Lat's halal restaurants."),
            ("stop", "~11.30", "🍽 Lunch — <b>Halal Food Da Lat</b>", "70 Hoàng Văn Thụ, Ward 5", "1h",
             "Open 07:30–20:30, about $5–10 a head. Eat before heading out west."),
            ("move", "~35 min southwest to Tà Nung", "", "", "", ""),
            ("stop", "~13.15", "Mongo Land", "Tà Nung commune — 17 km southwest", "2h",
             "Mongolian steppe as a theme park: yurts, horse riding, archery, nomad dress-up, rainbow slide, pet farm. <b>Closes 17:00.</b>"),
            ("stop", "~15.30", "KDL Sinh Thái Cao Nguyên Hoa", "Tà Nung area", "1h",
             "Flower-highland eco park, minutes down the same road. Confirm hours with the hotel — it's recent."),
            ("move", "~35 min back into the city", "", "", "", ""),
            ("stop", "~17.30", "Xuan Huong Lake", "City centre — walk from the hotel", "1h",
             "The lake loop as the light goes. Straight out of the hotel's front door."),
            ("stop", "~19.00", "🍽 Dinner — <b>Fatimah Restaurant</b>", "18–24 Nguyễn Du, Ward 9", "1.25h",
             "Halal Vietnamese with a prayer space. The better sit-down of Da Lat's two halal kitchens."),
            ("stop", "~20.30", "L'angfarm Center", "City centre", "45 min",
             "Dried fruit, artichoke tea, jam, coffee, macadamia — all packaged. <b>Buy the dawn snacks tonight</b>; you leave at 04.15 tomorrow."),
        ],
        notes=[
            "You climb from 30°C in Saigon to 17–24°C in Da Lat in under an hour. The jacket comes out of the bag today.",
            "<b>Alarm at 03.45.</b> Tomorrow starts before four for the cloud bridge.",
            "Ask reception tonight for a <b>breakfast box</b> and an 04.00 car — both need a day's notice.",
        ],
    ),
    dict(
        n="DAY 4", date="Friday, 11 September", title="Dawn on the cloud bridge, then Cầu Đất",
        color="#2E2E33",
        outfit="<b>Black leather + white</b> for the 04.15 start — it is genuinely cold up there",
        start="04.15", finish="~20.30", sleep=f"{H_DL} — night 4",
        compact=True,
        rows=[
            ("stop", "04.15", "Leave the hotel — take the breakfast box", "", "—", "Torch, jacket, flask. Nothing is open at this hour."),
            ("move", "~1 hour east through Trại Mát to Cầu Đất", "", "", "", ""),
            ("stop", "~05.15", "Cầu Gỗ Săn Mây — the cloud-hunting wooden bridge",
             "Cầu Đất tea hills, ~27 km east", "2h",
             "The wooden walkway out over the tea slopes with cloud sitting in the valley beneath it. Past Cầu Đất Farm, turn toward the lavender field, then three minutes on. <b>The picture of the trip.</b>"),
            ("stop", "~07.30", "Cầu Đất tea hills", "Cầu Đất, QL20", "1h",
             "Free to walk, and best in the leftover cloud. Eat the breakfast box up here."),
            ("stop", "~08.45", "Euro Garden Cầu Đất", "QL20, Cầu Đất — 25 km east", "2.5h",
             "7.2 ha at 1,650 m: seasonal flower fields, a miniature French castle, an Eiffel Tower, a railway café."),
            ("move", "DRIVE: back west to the city &mdash; ~45 min", "", "", "", ""),
            ("stop", "~12.15", "🍽 Lunch — <b>Fatimah Restaurant</b> 🕌", "18–24 Nguyễn Du, Ward 9", "1.5h",
             "<b>Today is Friday.</b> Fatimah has a prayer space — ask them at lunch about Jumu'ah, and time the morning so you're back by noon rather than one."),
            ("stop", "~14.15", "Crazy House (Hằng Nga)", "Huỳnh Thúc Kháng, city", "1.25h",
             "The tree-and-cave house. Narrow stairs and it gets busy — early afternoon works, mid-morning does not."),
            ("stop", "~15.45", "Back to the hotel — rest", f"{H_DL}", "2.5h",
             "Up since 03.45, and you drive to the coast tomorrow. Take the afternoon off properly."),
            ("stop", "~18.30", "🍽 Dinner — <b>Halal Food Da Lat</b>", "70 Hoàng Văn Thụ, Ward 5", "1.25h",
             "Be seated by 19:00 — <b>it closes at 20:30</b>."),
            ("stop", "~20.00", "Pack — you change city tomorrow", f"{H_DL}", "—", ""),
        ],
        notes=[
            "<b>Food needs planning today.</b> Nothing halal exists out at Cầu Đất, so the breakfast box travels with you and the first real meal is lunch back in town.",
            "The whole morning is one road east and back — no doubling. 04.00 pickup, booked last night.",
            "Cầu Đất is 1,650 m and cold before sunrise; by noon you'll want the t-shirt underneath.",
        ],
    ),
    dict(
        n="DAY 5", date="Saturday, 12 September", title="Hydrangeas, the coaster, then the pass to the sea",
        color="#D4749B",
        outfit="<b>Soft pink + white</b> — hydrangeas in the morning, red dunes at sunset",
        start="07.30", finish="~21.00", sleep=f"<b>Move</b> → {H_MN} — night 5",
        compact=True,
        rows=[
            ("stop", "07.30", f"Checkout — <b>{H_DL}</b>, bags into the car", "10 Phan Bội Châu", "20 min",
             "You leave the city after lunch, so settle up now and travel with the bags."),
            ("stop", "~08.00", "Trại Mát hydrangea fields", "Hoa Cẩm Tú Cầu street, Ward 3", "1.25h",
             "Hydrangea Street and the cẩm tú cầu fields along it. <b>They flower May to December</b> — out now, and morning is the good light."),
            ("move", "~20 min south on QL20", "", "", "", ""),
            ("stop", "~09.35", "Datanla — new alpine coaster", "QL20, ~5 km south", "1.25h",
             "The rebuilt coaster down through the forest, falls at the bottom. You control the brake — once slow for the video, once fast."),
            ("move", "~15 min", "", "", "", ""),
            ("stop", "~11.05", "Happy Hill", "Đá Tiên, Hoa Phượng Tím st, Ward 4 — 12 km", "1.25h",
             "Film-set park on Tuyen Lam lake: windmills, colour, staged photo corners. Open 07:00–17:30."),
            ("move", "~10 min", "", "", "", ""),
            ("stop", "~12.30", "Đường Hầm Điêu Khắc (Clay Tunnel)", "Tuyen Lam lake", "45 min",
             "A sculpted red-clay history of Da Lat — the whole city rebuilt in mud. Odd, and better than it sounds. <b>Drop this if you're running late.</b>"),
            ("stop", "~13.30", "🍽 Early lunch — <b>Halal Food Da Lat</b>, then go", "70 Hoàng Văn Thụ", "45 min",
             "Last halal meal until Mui Ne. Ten minutes back into town from Tuyen Lam, and on the way to the QL28B junction."),
            ("move", "DRIVE: Da Lat &rarr; Mui Ne on QL28B over the Đại Ninh pass &mdash; 155 km, 3.5&ndash;4 hours", "", "", "", ""),
            ("stop", "~18.15", f"Check in — <b>{H_MN}</b>", "Ham Tien beach strip, Mui Ne", "45 min",
             "Check-in 14:00, so you're well clear. Beachfront, tropical gardens, well-known spa."),
            ("stop", "~19.30", "🍽 Dinner — <b>Mughal House Indian Halal</b>", "246/2B Nguyễn Đình Chiểu", "1.5h",
             "Halal Indian on the main strip, minutes from the resort. Book the 05.00 dune jeep at reception tonight."),
        ],
        notes=[
            "<b>Leave Da Lat by 14.30 at the latest</b> — QL28B comes down the Đại Ninh pass and you want that in daylight.",
            "The Red Dunes sunset falls out of today because of the drive. You catch the White Dunes at sunrise tomorrow instead, which is the better of the two.",
            "17°C at breakfast, 31°C at dinner. Jacket to the bottom of the bag after this morning — you won't need it again.",
        ],
    ),
    dict(
        n="DAY 6", date="Sunday, 13 September", title="White dunes at sunrise, then home",
        color="#1E7FA8",
        outfit="<b>Blue + yellow</b> — sand and sky, then travel in it",
        start="05.00", finish="KUL", sleep="—",
        rows=[
            ("stop", "05.00", "White Sand Dunes (Bàu Trắng) — sunrise",
             "~35 km northeast, ~45 min", "2.5h",
             "The pale dunes, the only real desert in Vietnam. Sunrise is cool, empty, and the entire point. Jeeps wait at the gate — <b>agree the price, and per person or per vehicle, before getting in</b>."),
            ("stop", "~07.45", "Bàu Trắng lotus lake", "Beside the dunes", "30 min",
             "Freshwater lake hard against the sand, fringed with lotus. Water, lotus and desert in one frame."),
            ("move", "~45 min back to Ham Tien", "", "", "", ""),
            ("stop", "~09.15", "🍽 Breakfast, shower, checkout", f"{H_MN}", "1.5h",
             "Checkout is 12:00 so there's no rush. Rinse the sand off properly — you're about to sit in a car for three hours and a plane for two."),
            ("stop", "~10.45", "Fairy Stream (Suối Tiên) — if you want it", "Ham Tien, off the main road", "1h",
             "Wade barefoot up a warm ankle-deep stream between red and white sandstone walls. <b>Optional</b> — skip it if you'd rather have the buffer."),
            ("move", "DRIVE: Mui Ne &rarr; Saigon on the Dầu Giây&ndash;Phan Thiết expressway &mdash; 200&ndash;220 km, 2.5&ndash;3 hours", "", "", "", ""),
            ("stop", "~15.00", "🍽 Late lunch — Đông Du street", "District 1, Saigon", "1h",
             "Full circle, back to the halal street you started on. Last proper meal before the flight."),
            ("stop", "~16.30", "Check-in + immigration", "Tan Son Nhat T2", "2h buffer",
             "International departures. Saigon traffic is the variable, not the airport."),
            ("stop", "evening", "SGN → KUL — Malaysia Airlines", "Tan Son Nhat T2", "~2h",
             "MH750 / MH758 / MH766. <b>Book an evening departure — 19:00 or later</b> — so the drive and the dunes both have slack. Malaysia is 1 hour ahead."),
        ],
        notes=[
            "<b>This day works only with an evening flight.</b> Check the MAS timetable before you commit to the sunrise dunes; if the only seats are early afternoon, drop the dunes and drive at 07.00 instead.",
            "Two tickets, one journey: the Da Lat hop is domestic and separate from the MAS legs. Nothing connects them, so keep the slack.",
            "Sand gets everywhere. Pack the dune clothes in a separate bag before you get in the car.",
        ],
    ),
]

TRIP = dict(
    doc_title="Saigon, Da Lat &amp; Mui Ne — 8-13 September 2026",
    kicker="Halal-only meals &middot; cafés removed from the list &middot; Bandung is off (Anak Krakatau)",
    title="Saigon &rarr; Da Lat &rarr; Mui Ne<br>8 &ndash; 13 September 2026",
    subtitle=(f"{GUESTS} &middot; Malaysia Airlines both ways, one domestic hop &middot; six days, five nights<br>"
              "2 nights Saigon, 2 nights Da Lat, 1 night Mui Ne. Every meal is a halal address."),
    travellers=GUESTS,
    country="Vietnam",
    no_map=("Breakfast", "Lunch", "Dinner", "Late lunch", "Early lunch", "Check in", "Checkout",
            "Leave the", "Back to the", "Pack", "KUL →", "SGN →", "DLI →", "🍽", "🕌"),
    summary_title="The Six Days",
    summary_head=("Day", "Date", "Where you sleep", "The point of the day", "Outfit"),
    summary_rows=[
        ("Day 1", "Tue, 8 Sep", "Alagon Saigon", "Fly in, Nguyễn Huệ, Café Apartment", "Soft blue + brown"),
        ("Day 2", "Wed, 9 Sep", "Alagon Saigon", "Post office, Book Street, Bến Thành, Skydeck", "Cream fairytale"),
        ("Day 3", "Thu, 10 Sep", "<b>Fly</b> → Hôtel Colline", "Up to Da Lat, Tà Nung, the lake", "Khaki + black"),
        ("Day 4", "Fri, 11 Sep", "Hôtel Colline", "Cloud bridge at dawn, Cầu Đất, Crazy House", "Black leather + white"),
        ("Day 5", "Sat, 12 Sep", "<b>Drive</b> → Bamboo Village", "Hydrangeas, coaster, Happy Hill, the pass", "Soft pink + white"),
        ("Day 6", "Sun, 13 Sep", "—", "White dunes at sunrise, then home", "Blue + yellow"),
    ],
    book_now_head="Book Tonight, In This Order",
    book_now=[
        ("MAS KUL → SGN on 8 Sept, and SGN → KUL on 13 Sept <b>in the evening</b>",
         "MH750 / MH758 / MH766, ~7 a day. The evening return is what makes the sunrise dunes possible — check it before committing to that morning."),
        ("SGN → Da Lat on 10 Sept, 07:00–09:00",
         "Vietnam Airlines or Vietjet, 55 min, six a day. Domestic, so no immigration either end."),
        (f"<b>Alagon Saigon Hotel &amp; Spa</b> — 2 nights, 8–10 Sept",
         "4★ District 1, by Đông Du street — <b>the Saigon Central Mosque is on it</b>, with a dozen halal restaurants. In 14:00, out 12:00."),
        (f"<b>Hôtel Colline Dalat</b> — 2 nights, 10–12 Sept",
         "4★, 10 Phan Bội Châu — 200 m from Xuan Huong Lake, walkable to both halal kitchens. In 14:00, out 12:00."),
        (f"<b>Bamboo Village Beach Resort &amp; Spa</b> — 1 night, 12–13 Sept",
         "4★ beachfront on the Ham Tien strip, gardens and a well-known spa. In 14:00, out 12:00."),
        ("Cars: three bookings",
         "11 Sept <b>04.00 pickup</b>, all day east. 12 Sept Da Lat → Mui Ne on <b>QL28B</b>, ~14.30. 13 Sept Mui Ne → Saigon."),
        ("A jeep for the white dunes on the 13th",
         "05.00 start — book it at Bamboo Village reception on the 12th. Agree the price up front."),
        ("Cancel the Bandung side",
         "Holiday Inn Pasteur, Swiss-Belresort Dago, Fairfield CGK — ask for a waiver citing the closure. Message Kiki, re-issue the insurance."),
    ],
    know_cols=3,
    good_to_know=[
        ("Halal", "Easiest in Saigon — the hotel is by the mosque. Two halal kitchens in Da Lat, two in Mui Ne. See the food page."),
        ("Visa", "Visa-free for Malaysians, 30 days. Carry hotel bookings and onward tickets."),
        ("Three climates", "Saigon 30°C+ and humid; Da Lat 17–24°C, cold before dawn; Mui Ne 25–31°C and bright."),
        ("Money", "Vietnamese dong. Cash for entry tickets (100–120k a head), the dune jeep and the markets."),
        ("Getting around", "Grab in Saigon and Da Lat; a booked car for the Da Lat clusters and both long drives."),
        ("Friday 11 Sept", "Jumu'ah falls on the Da Lat day. Fatimah has a prayer space — lunch is booked around it."),
    ],
    sign=("<b>MAS out:</b> _____________ &nbsp; <b>SGN → DLI:</b> _____________ &nbsp; "
          "<b>MAS home (evening):</b> _____________ &nbsp; <b>Alagon:</b> _____________<br>"
          "<b>Colline:</b> _____________ &nbsp; <b>Bamboo Village:</b> _____________ &nbsp; "
          "<b>Drivers:</b> _____________ &nbsp; <i>Checked 6 Sept 2026.</i>"),
    days=DAYS,
    extra_pages=[
        dict(
            color="#B23A16",
            kicker="EAT",
            title="Halal food — every meal on this trip",
            subtitle="Saigon is easy. Da Lat has exactly two. Plan the Cầu Đất day around that.",
            col_heads=("Place", "Where", "What to know"),
            rows=[
                ("Đông Du street", "District 1, Saigon — your hotel's street",
                 "<b>Saigon Central Mosque is here</b>, with a dozen halal restaurants around it. Days 1, 2 and 6 all eat on this street; nothing is more than five minutes from the Alagon."),
                ("Fatimah Restaurant", "18–24 Nguyễn Du, Ward 9, Da Lat",
                 "<b>Halal Vietnamese, with a prayer space.</b> Day 3 dinner and Day 4's Friday lunch — ask them about Jumu'ah when you sit down."),
                ("Halal Food Da Lat", "70 Hoàng Văn Thụ, Ward 5, Da Lat",
                 "<b>Open 07:30–20:30</b>, ~$5–10 a head. Day 3 lunch, Day 4 dinner, Day 5's early lunch. Note the early close — be seated by 19:00."),
                ("Mughal House Indian Halal", "246/2B Nguyễn Đình Chiểu, Mui Ne",
                 "<b>Halal Indian on the Ham Tien strip</b>, minutes from Bamboo Village. Day 5 dinner."),
                ("T'HALAL Restaurant", "63A Huỳnh Thúc Kháng, Phan Thiết",
                 "Vietnamese halal and seafood, ~20 min down the coast. The spare option if you want a second Mui Ne meal. 100–300k VND."),
                ("Vegetarian (chay) restaurants", "Da Lat city — several",
                 "The late-night fallback: Thiền Duyên, Tu Hạnh, Thanh Tịnh, Hoa Sen. No meat at all, so no question about the meat."),
                ("Hotel breakfast", "All three hotels",
                 "Included everywhere. Eggs, bread, fruit, noodles without the pork broth. Ask Colline for a <b>breakfast box on the 11th</b> — you leave at 04.15."),
                ("Snacks from L'angfarm", "Da Lat city centre",
                 "Packaged dried fruit, nuts, biscuits — buy on the evening of the 10th for the dawn drives on the 11th and 13th."),
            ],
            notes=[
                "<b>Day 4 is the one to plan for.</b> Out east from 04.15 with nothing halal near Cầu Đất — the breakfast box travels with you and lunch waits until noon back in town.",
                "Every café and restaurant from your original Da Lat list stays off the plan, so there is no venue on it where you have to ask about the kitchen.",
                "Saigon has an official city halal restaurant list published by the tourism department if you want more choice than Đông Du.",
            ],
            notes_head="How to eat on this trip",
            foot="halal food",
        ),
        dict(
            color="#15764F",
            kicker="SLEEP",
            title="The three hotels",
            subtitle="All 4★, each chosen for position rather than luxury",
            no_maps=True,
            col_heads=("Hotel", "Dates", "Why this one, and how to book"),
            rows=[
                ("<b>Alagon Saigon Hotel &amp; Spa</b> — 4★", "In Tue 8 Sept<br>Out Thu 10 Sept",
                 "District 1, beside <b>Đông Du street — the Saigon Central Mosque is on it</b>, and so are a dozen halal restaurants. Known among Muslim travellers for exactly that. Walking distance to Nguyễn Huệ, the post office, Bến Thành and the Skydeck, so days 1 and 2 need no car at all. In 14:00, out 12:00. <a href='https://www.google.com/search?q=Alagon+Saigon+Hotel+and+Spa+booking'>Find it &amp; book</a>"),
                ("<i>Alternative:</i> Saigon Hotel, Đông Du", "same dates",
                 "Literally on Đông Du, steps from the mosque and Đồng Khởi. Simpler than the Alagon but the position is unbeatable. <a href='https://www.google.com/search?q=Saigon+Hotel+Dong+Du+District+1+booking'>Find it &amp; book</a>"),
                ("<b>Hôtel Colline Dalat</b> — 4★", "In Thu 10 Sept<br>Out Sat 12 Sept",
                 "10 Phan Bội Châu, city centre. <b>200 m from Xuan Huong Lake</b> and walkable to both halal kitchens — which matters more here than anywhere, because there are only two. Opened 2019, rated ~8.8. Every cluster radiates from this point: Cầu Đất east, Tà Nung west, Datanla south. In 14:00, out 12:00. <a href='https://www.google.com/search?q=Hotel+Colline+Dalat+booking'>Find it &amp; book</a>"),
                ("<i>Alternative:</i> Muong Thanh Holiday Da Lat — 4★", "same dates",
                 "42 Phan Bội Châu, same street, same distance to the lake. Bigger, chain-run, indoor pool and spa. <a href='https://www.google.com/search?q=Muong+Thanh+Holiday+Da+Lat+booking'>Find it &amp; book</a>"),
                ("<b>Bamboo Village Beach Resort &amp; Spa</b> — 4★", "In Sat 12 Sept<br>Out Sun 13 Sept",
                 "Ham Tien beach strip. Beachfront, family-run since 1998, thatched villas in tropical gardens, and one of the best-regarded spas in Mui Ne. Minutes from Mughal House and Fairy Stream; the dune jeep collects from the door. In 14:00, out 12:00. <a href='https://www.google.com/search?q=Bamboo+Village+Beach+Resort+Mui+Ne+booking'>Find it &amp; book</a>"),
                ("<i>Alternative:</i> The Sailing Bay Beach Resort — 4★", "same dates",
                 "Also Ham Tien: 2.5 hectares of garden, big seaside pool, 192 rooms. More resort, less village. <a href='https://www.google.com/search?q=Sailing+Bay+Beach+Resort+Mui+Ne+booking'>Find it &amp; book</a>"),
                ("Browse each area", "—",
                 "<a href='https://www.booking.com/landmark/vn/xuan-huong-lake.html'>Da Lat — hotels near Xuan Huong Lake</a> &nbsp;·&nbsp; <a href='https://www.booking.com/city/vn/mui-ne.html'>All Mui Ne hotels</a>"),
            ],
            notes=[
                "I have not checked live rates or availability for your dates — confirm all three before booking flights around them.",
                "In Da Lat ask for a room off the street: the centre is noisy late and you are up at 03.45 on the 11th.",
                "At Bamboo Village, book the dune jeep and the Saigon car <b>at check-in on the 12th</b> — cheaper than arranging either from Malaysia.",
                "No hotel here is halal-certified. Breakfast is easy to navigate; every other meal is on the food page.",
            ],
            notes_head="Booking notes",
            foot="hotels",
        ),
        dict(
            color="#6D2E5B",
            kicker="CUT",
            title="Removed from your list — and what still didn't fit",
            subtitle="Every café and restaurant is out, as you asked. Here is exactly what went, and why.",
            no_maps=True,
            col_heads=("Place", "What it is", "Why it's not in the plan"),
            rows=[
                ("Miền Du Mục · Thác Mây &amp; Chill · Suối Bình Yên · Reply 1994 · Haiyih Coffee",
                 "cafés", "<b>Removed — not halal kitchens.</b> Four were load-bearing, and all four are covered: the Cầu Gỗ bridge replaces Thác Mây at dawn and is better; the Cầu Đất tea hills replace Haiyih on the same hill; the hydrangea fields survive without Suối Bình Yên on their street."),
                ("Giấc Mơ Đà Lạt · Rừng Mơ · Dream Garden · The Forest · The Wilder Nest · Rừng Thông Mơ",
                 "cafés, café-homestays, a bistro", "<b>Removed — not halal kitchens.</b> Dream Garden was the Tà Nung stop; Mongo Land and Cao Nguyên Hoa cover that road on Day 3."),
                ("Da Lat Night Market", "street-food market",
                 "<b>Removed.</b> It is a food market and the grilled stalls are the point of it. L'angfarm, two minutes away, covers the shopping."),
                ("Floating Town · Lạc Hư Cổ Trấn", "ticketed photo parks with a café",
                 "<b>Removed on the same rule</b> — the entry fee is a drink, so they work as cafés. <b>Say the word and both come back</b>: taking the included drink and no food is a defensible line. Floating Town joins Day 3 in Tà Nung; Lạc Hư joins Day 4 coming back from Cầu Đất."),
                ("Pink Valley + Langbiang", "flower valley + mountain, Lạc Dương, 12–22 km north",
                 "<b>Still no day for them.</b> The extra day went to Saigon, so Da Lat is two days again. <b>Straight swap available:</b> drop Tà Nung on Day 3 and go north instead — Pink Valley and Langbiang are ten minutes apart. Say which pair you'd rather have."),
                ("Auro Garden", "unclear",
                 "Almost certainly <b>Euro Garden Cầu Đất</b>, already on Day 4. If you meant something else, tell me."),
                ("Cầu Gỗ", "wooden bridge",
                 "<b>Already in — Day 4 at dawn.</b> Same place as 'Cầu Đất Cloud Hunting Wooden Bridge' on your list."),
                ("Mekong Delta day trip", "My Tho / Ben Tre, ~2h each way from Saigon",
                 "The alternative Day 2 if you'd rather have countryside than city: floating market, sampans, coconut workshops — and pink water lilies, since this is flood season. <b>Arrange halal food yourself</b>; tour lunches are not."),
            ],
            notes=[
                "Fourteen entries came off the list: twelve cafés and a bistro, the night market, and the two ticketed café-parks.",
                "<b>The one real casualty is the north cluster</b>, and it's a straight swap against Tà Nung rather than a loss — tell me which pair you want and I'll switch Day 3.",
                "If a stop closes or disappoints, pull the nearest swap from this page rather than driving somewhere new.",
            ],
            notes_head="What this cost, honestly",
            foot="removed + spare",
        ),
    ],
)

if __name__ == "__main__":
    engine.write(TRIP,
                 os.path.join(OUT_DIR, "Itinerary-Saigon-DaLat-MuiNe.html"),
                 os.path.join(OUT_DIR, "Itinerary-Saigon-DaLat-MuiNe.pdf"))
