#!/usr/bin/env python3
"""Saigon → Da Lat → Mui Ne, 8-13 September 2026.

Six days, five nights: two in Saigon, two in Da Lat, one in Mui Ne. Non-halal
cafés and restaurants stay off the list; every meal is a halal address, and in
Saigon the hotel sits by the Central Mosque on Đông Du street.

Run:    python3 dalat-muine-saigon/build_trip_pdf.py
Output: dalat-muine-saigon/Itinerary-Saigon-DaLat-MuiNe.html  +  .pdf
"""

import os
import sys

sys.path.insert(0, os.path.join(os.path.dirname(os.path.abspath(__file__)), ".."))
from trips import itinerary_pdf as engine  # noqa: E402

OUT_DIR = os.path.dirname(os.path.abspath(__file__))
GUESTS = "Haris Haikal &amp; Aina Izzaty"
H_SGN = "Alagon Saigon Hotel &amp; Spa"
H_DL = "La Fleur Premium Central Apartment"
H_MN = "The Cliff Resort &amp; Residences"

DAYS = [
    dict(
        n="DAY 1", date="Tuesday, 8 September", title="MH750 to Saigon — market, post office, boulevard",
        color="#46688C",
        outfit="<b>Soft blue + brown</b> — café theme, wear it off the plane",
        start="08.55 from KLIA", finish="~21.00", sleep=f"{H_SGN} — 8→9 Sept",
        compact=True,
        rows=[
            ("stop", "08.55", "KUL → SGN — <b>MH750</b>, Malaysia Airlines", "KLIA", "2h 05m",
             "Lands <b>10:00 Saigon time</b>. Vietnam is 1 hour behind Malaysia, so you gain the morning."),
            ("move", "Driver meets you &mdash; Tan Son Nhat &rarr; District 1, 8 km, 30&ndash;45 min", "", "", "", ""),
            ("stop", "~11.15", f"Drop bags — <b>{H_SGN}</b>", "District 1, by Đông Du street", "30 min",
             "Room is from 14:00, so leave the bags and go. The <b>Saigon Central Mosque is on Đông Du</b>, with a dozen halal restaurants around it."),
            ("stop", "~12.00", "🍽 Lunch — Đông Du street", "District 1, by the mosque", "1.25h",
             "First meal of the trip, two minutes from the hotel. The easiest halal eating you'll get — Da Lat has only two kitchens."),
            ("stop", "~13.30", "Bến Thành Market + Saigon Square", "District 1", "1.75h",
             "Souvenirs, dried fruit, clothes and bags. Bargain hard — open at about 40% of the asking price. The early landing is what buys you this."),
            ("stop", "~15.45", "Saigon Central Post Office", "Công xã Paris, District 1", "1h",
             "Gustave Eiffel-era ironwork, painted tiles and the old wall maps — still a working post office, so send yourselves a postcard. <b>Shuts around 19:00</b>, so it goes before the café."),
            ("move", "~10 min walk down to the river end", "", "", "", ""),
            ("stop", "~17.00", "Nguyễn Huệ walking street", "District 1", "45 min",
             "The wide pedestrian boulevard up to the old City Hall."),
            ("stop", "~17.50", "The Café Apartment, 42 Nguyễn Huệ", "Nguyễn Huệ", "1.25h",
             "A nine-storey 1960s block where every flat is a café or tiny shop with a balcony over the street. Lift to the top, walk down — you'll catch the light going. <b>Photos and the view</b>; eat at Đông Du."),
            ("stop", "~19.15", "🍽 Dinner — Đông Du street", "District 1, by the mosque", "1.5h", ""),
            ("stop", "~20.45", "Early night, repack", f"{H_SGN}", "—",
             "VN1382 leaves at 10:20 tomorrow. Repack so the Da Lat bag is the one you live out of."),
        ],
        notes=[
            "<b>MH750 lands at 10:00</b>, which gives you a genuine first day rather than an arrival evening — hence the market going in.",
            "Saigon in September is hot, humid and gets a heavy shower most afternoons that clears within the hour. Bến Thành and the Café Apartment are both fine in rain.",
            "<b>Saigon is one night by design</b> — land, look around, sleep, fly up to the mountains.",
        ],
    ),
    dict(
        n="DAY 2", date="Wednesday, 9 September", title="VN1382 up to Da Lat — Tà Nung, then the lake",
        color="#6B6A52",
        outfit="<b>Khaki + black</b> — travel morning, and it suits the steppe at Mongo Land",
        start="07.45", finish="~21.15", sleep=f"{H_DL} — 9→12 Sept",
        compact=True,
        rows=[
            ("stop", "07.45", f"Checkout — <b>{H_SGN}</b>", "District 1", "30 min",
             "Checkout is 12:00 but the flight is mid-morning. Ask for breakfast early or boxed."),
            ("stop", "10.20", "SGN → DLI — <b>VN1382</b>, Vietnam Airlines", "Tan Son Nhat T1", "~50 min",
             "Lands Lien Khuong <b>~11:10</b>. Domestic terminal, so no immigration — the simplest leg of the trip."),
            ("move", "Driver meets you at Lien Khuong &mdash; 30 km to the city, ~40 min", "", "", "", ""),
            ("stop", "~12.15", f"Drop bags — <b>{H_DL}</b>", "5–7A Trần Phú, Ward 3", "30 min",
             "Room from 14:00, so bags down and out. <b>Trần Phú runs along Xuan Huong Lake</b> — the lake is at your front door, and the market is a 15-minute walk. You're here three nights, so unpack properly tonight."),
            ("stop", "~12.50", "🍽 Lunch — <b>Halal Food Da Lat</b>", "70 Hoàng Văn Thụ, Ward 5", "1h",
             "Open 07:30–20:30, about $5–10 a head. A few minutes by Grab. Eat before heading west."),
            ("move", "~35 min southwest to Tà Nung", "", "", "", ""),
            ("stop", "~14.30", "Mongo Land", "Tà Nung commune — 17 km southwest", "1.5h",
             "Mongolian steppe as a theme park: yurts, horse riding, archery, nomad dress-up, rainbow slide, pet farm. <b>Closes 17:00</b>, so this is the tight one today."),
            ("stop", "~16.15", "KDL Sinh Thái Cao Nguyên Hoa", "Tà Nung area", "45 min",
             "Flower-highland eco park, minutes down the same road. Confirm hours with the hotel — it's recent."),
            ("move", "~35 min back into the city", "", "", "", ""),
            ("stop", "~17.45", "Xuan Huong Lake", "Trần Phú — outside the hotel", "1h",
             "The lake loop as the light goes. You are staying on the lake road, so this costs you no travel at all."),
            ("stop", "~19.00", "🍽 Dinner — <b>Fatimah Restaurant</b>", "18–24 Nguyễn Du, Ward 9", "1.25h",
             "Halal Vietnamese with a prayer space. The better sit-down of Da Lat's two halal kitchens."),
            ("stop", "~20.30", "L'angfarm Center", "City centre", "45 min",
             "Dried fruit, artichoke tea, jam, coffee, macadamia — all packaged. <b>Buy the dawn snacks tonight</b>; you leave at 04.15 tomorrow."),
        ],
        notes=[
            "You climb from 30°C in Saigon to 17–24°C in Da Lat inside an hour. The jacket comes out of the bag today.",
            "<b>Alarm at 03.45.</b> Tomorrow starts before four for the cloud bridge — tell your driver tonight to be outside at 04.00.",
            "Ask the hotel this evening for a <b>breakfast box</b> for tomorrow; nothing is open when you leave.",
        ],
    ),
    dict(
        n="DAY 3", date="Thursday, 10 September", title="Dawn on the cloud bridge, then Cầu Đất",
        color="#2E2E33",
        outfit="<b>Black leather + white</b> for the 04.15 start — it is genuinely cold up there",
        start="04.15", finish="~20.00", sleep=f"{H_DL} — night 2 of 3",
        compact=True,
        rows=[
            ("stop", "04.15", "Leave with the driver — take the breakfast box", "", "—",
             "Torch, jacket, flask. Nothing is open at this hour."),
            ("move", "~1 hour east through Trại Mát to Cầu Đất", "", "", "", ""),
            ("stop", "~05.15", "Cầu Gỗ Săn Mây — the cloud-hunting wooden bridge",
             "Cầu Đất tea hills, ~27 km east", "2h",
             "The wooden walkway out over the tea slopes with cloud sitting in the valley beneath it. Past Cầu Đất Farm, turn toward the lavender field, then three minutes on. <b>The picture of the trip.</b>"),
            ("stop", "~07.30", "Cầu Đất tea hills", "Cầu Đất, QL20", "1.25h",
             "Free to walk, and best in the leftover cloud. Eat the breakfast box up here."),
            ("stop", "~09.00", "Euro Garden Cầu Đất", "QL20, Cầu Đất — 25 km east", "3h",
             "7.2 ha at 1,650 m: seasonal flower fields, a miniature French castle, an Eiffel Tower, a railway café. You have the whole morning — take it slowly."),
            ("move", "~45 min back west to the city", "", "", "", ""),
            ("stop", "~13.00", "🍽 Late lunch — <b>Halal Food Da Lat</b>", "70 Hoàng Văn Thụ, Ward 5", "1h", ""),
            ("stop", "~14.15", "Back to the hotel — sleep it off", f"{H_DL}", "3.5h",
             "Up since 03.45. Take the afternoon properly off — there is nothing here worth being wrecked for."),
            ("stop", "~18.00", "🍽 Dinner — <b>Fatimah Restaurant</b>", "18–24 Nguyễn Du, Ward 9", "1.5h", ""),
            ("stop", "~19.45", "Quiet evening", f"{H_DL}", "—", "Tomorrow is a normal start — no alarm before seven."),
        ],
        notes=[
            "<b>Food needs planning today.</b> Nothing halal exists out at Cầu Đất, so the breakfast box travels with you and the first real meal is a late lunch back in town.",
            "The whole morning is one road east and back — no doubling. Driver outside at 04.00.",
            "Cầu Đất is 1,650 m and cold before sunrise; by noon you'll want the t-shirt underneath.",
        ],
    ),
    dict(
        n="DAY 4", date="Friday, 11 September", title="Hydrangeas, Jumu'ah, then the rose valley",
        color="#D4749B",
        outfit="<b>Soft pink + white</b> — hydrangea fields in the morning, rose valley after prayers",
        start="07.45", finish="~20.30", sleep=f"{H_DL} — night 3 of 3",
        compact=True,
        rows=[
            ("stop", "07.45", "Trại Mát hydrangea fields", "Hoa Cẩm Tú Cầu street, Ward 3", "1.5h",
             "Hydrangea Street and the cẩm tú cầu fields along it. <b>They flower May to December</b> — out now, and morning is the good light."),
            ("move", "~20 min back into the centre", "", "", "", ""),
            ("stop", "~09.45", "Crazy House (Hằng Nga)", "Huỳnh Thúc Kháng, city", "1.25h",
             "The tree-and-cave house. Narrow stairs, and it fills up later — this is the right slot for it."),
            ("stop", "~11.45", "🕌🍽 Jumu'ah + lunch — <b>Fatimah Restaurant</b>",
             "18–24 Nguyễn Du, Ward 9", "1.5h",
             "<b>Today is Friday.</b> Fatimah has a prayer space, and the morning is deliberately kept in town so you're back in good time. Ask them about the timing on Wednesday night."),
            ("move", "~40 min north to Lạc Dương", "", "", "", ""),
            ("stop", "~14.00", "Pink Valley (Thung Lũng Hồng)", "Lat village, Lạc Dương — 22 km north", "2h",
             "A rose valley done as a romantic European garden. 100,000 VND entry, <b>open 07:00–17:00</b>. Pink and white here is the obvious pairing."),
            ("move", "~15 min", "", "", "", ""),
            ("stop", "~16.15", "Langbiang", "Lạc Dương — ~12 km north of the city", "1.5h",
             "The mountain over Da Lat. Take the jeep up to the Radar Peak viewpoint rather than walking. Cloud comes and goes — wait it out with a coffee at the top."),
            ("move", "~30 min back into the city", "", "", "", ""),
            ("stop", "~18.30", "🍽 Dinner — <b>Halal Food Da Lat</b>", "70 Hoàng Văn Thụ, Ward 5", "1.25h",
             "Be seated by 19:00 — <b>it closes at 20:30</b>."),
            ("stop", "~20.00", "Pack — you leave Da Lat tomorrow", f"{H_DL}", "—", ""),
        ],
        notes=[
            "<b>This is the day the third Da Lat night bought you.</b> Pink Valley and Langbiang are ten minutes apart in Lạc Dương, and both were cut from every earlier version of this trip.",
            "The morning stays in town on purpose, so Friday prayers aren't a scramble back from somewhere 40 minutes out.",
            "Pink Valley shuts at 17:00 — if the morning overruns, do Langbiang first and Pink Valley second.",
        ],
    ),
    dict(
        n="DAY 5", date="Saturday, 12 September", title="South on the way out, then the pass",
        color="#A8763A",
        outfit="<b>Cream fairytale</b> — the clay city and the film-set park",
        start="08.00", finish="~21.00", sleep="<b>Move</b> → The Cliff — 12→13 Sept",
        compact=True,
        rows=[
            ("stop", "08.00", "Checkout — <b>La Fleur</b>, bags into the car", "5–7A Trần Phú", "20 min",
             "You leave the city after lunch, so settle up now and travel with the bags."),
            ("move", "~15 min south on QL20", "", "", "", ""),
            ("stop", "~08.45", "Datanla — new alpine coaster", "QL20, ~5 km south", "1.25h",
             "The rebuilt coaster down through the forest, falls at the bottom. You control the brake — once slow, once fast."),
            ("move", "~15 min", "", "", "", ""),
            ("stop", "~10.15", "Đường Hầm Điêu Khắc (Clay Tunnel)", "Tuyen Lam lake", "1.25h",
             "A sculpted red-clay history of Da Lat — the whole city rebuilt in mud. Odd, and better than it sounds."),
            ("move", "~10 min", "", "", "", ""),
            ("stop", "~11.45", "Happy Hill", "Đá Tiên, Hoa Phượng Tím st, Ward 4 — 12 km", "1.25h",
             "Film-set park on Tuyen Lam lake: windmills, colour, staged photo corners. Open 07:00–17:30."),
            ("stop", "~13.15", "🍽 Early lunch — <b>Halal Food Da Lat</b>, then go",
             "70 Hoàng Văn Thụ, Ward 5", "45 min",
             "Last halal meal until the coast. Ten minutes from Tuyen Lam, and on the way to the QL28B junction."),
            ("move", "DRIVE: Da Lat &rarr; Phan Thiết on QL28B over the Đại Ninh pass &mdash; ~150 km, 3.5&ndash;4 hours", "", "", "", ""),
            ("stop", "~17.15", "Check in — <b>The Cliff Resort</b>", "5 Nguyễn Đình Chiểu, Phú Hài", "30 min",
             "Check-in 14:00, so the room is ready. You're at the <b>Phan Thiết end</b> of the strip — closer to town and to T'HALAL, a little further from the dunes."),
            ("move", "~20&ndash;25 min up the coast road", "", "", "", ""),
            ("stop", "~18.15", "Red Sand Dunes (Đồi Hồng) for sunset", "Mui Ne end of the strip", "1h",
             "Orange dunes right beside the road, at their best in the last hour of light."),
            ("stop", "~19.45", "🍽 Dinner — <b>T'HALAL Restaurant</b>", "63A Huỳnh Thúc Kháng, Phan Thiết", "1.5h",
             "Vietnamese halal and seafood, ~10 minutes from The Cliff — your hotel's position makes this the easy dinner."),
        ],
        notes=[
            "<b>Leave Da Lat by 14.15 at the latest</b> — QL28B comes down the Đại Ninh pass and you want that in daylight.",
            "Sunset is tight against the drive: if you run late, go straight to the dunes and check in afterwards. 17°C at breakfast, 31°C at dinner — jacket to the bottom of the bag.",
            "<b>Tell your driver tonight: 04.45 tomorrow.</b> The White Dunes are ~60 minutes from Phú Hài.",
        ],
    ),
    dict(
        n="DAY 6", date="Sunday, 13 September", title="White dunes at sunrise, then MH767 home",
        color="#1E7FA8",
        outfit="<b>Blue + yellow</b> — sand and sky, then travel in it",
        start="04.45", finish="KUL ~22.15", sleep="—",
        compact=True,
        rows=[
            ("stop", "04.45", "Leave for the White Sand Dunes", f"{H_MN}", "—",
             "Sunrise is around 05:45 and the dunes are ~60 min from Phú Hài, so this is the honest departure time."),
            ("stop", "~05.45", "White Sand Dunes (Bàu Trắng) — sunrise",
             "~45 km northeast of Phan Thiết", "2h",
             "The pale dunes, the only real desert in Vietnam. Cool, empty, and the entire point. Jeeps wait at the gate — <b>agree the price, and per person or per vehicle, before getting in</b>."),
            ("stop", "~07.45", "Bàu Trắng lotus lake", "Beside the dunes", "30 min",
             "Freshwater lake hard against the sand, fringed with lotus. Water, lotus and desert in one frame."),
            ("move", "~1 hour back to Phú Hài", "", "", "", ""),
            ("stop", "~09.30", f"🍽 Breakfast, shower, checkout — <b>{H_MN}</b>", "Phú Hài", "2.5h",
             "Checkout is 12:00 and you have the time — rinse the sand off properly. Three hours in a car and two on a plane are next."),
            ("stop", "~12.15", "🍽 Early lunch — <b>T'HALAL</b> before the road", "63A Huỳnh Thúc Kháng, Phan Thiết", "45 min",
             "Ten minutes away. Eat here rather than gambling on the expressway."),
            ("move", "DRIVE: Phan Thiết &rarr; Saigon on the Dầu Giây expressway &mdash; ~200 km, 2.5&ndash;3 hours", "", "", "", ""),
            ("stop", "17.25", "Check-in + immigration", "Tan Son Nhat T2", "2h",
             "Two hours before an international departure. You should reach Saigon around 16:15 — the spare hour sits here, so if the drive ran clean take a coffee, and if it didn't, go straight in. Traffic is the variable, not the airport."),
            ("stop", "19.25", "SGN → KUL — <b>MH767</b>, Malaysia Airlines", "Tan Son Nhat T2", "~1h 50m",
             "Departs <b>19:25</b>, lands KLIA <b>~22:15</b>. Malaysia is 1 hour ahead, so the clock jumps an hour on landing."),
        ],
        notes=[
            "<b>The evening flight is what makes this day work</b> — sunrise dunes and a 200 km drive with hours to spare.",
            "Sand gets everywhere. Bag the dune clothes separately before you get in the car.",
        ],
    ),
]

TRIP = dict(
    doc_title="Saigon, Da Lat &amp; Mui Ne — 8-13 September 2026",
    kicker="Booked and confirmed &middot; halal-only meals &middot; driver arranged",
    title="Saigon &rarr; Da Lat &rarr; Mui Ne<br>8 &ndash; 13 September 2026",
    subtitle=(f"{GUESTS} &middot; MH750 out, MH767 home, VN1382 up to Da Lat &middot; six days, five nights<br>"
              "1 night Saigon, <b>3 nights Da Lat</b>, 1 night Phan Thiết. Every meal is a halal address."),
    travellers=GUESTS,
    country="Vietnam",
    no_map=("Breakfast", "Lunch", "Dinner", "Late lunch", "Early lunch", "Check in", "Checkout",
            "Leave with", "Leave for", "Back to the", "Pack", "Drop bags", "Early night",
            "Quiet evening", "Arrive Saigon", "KUL →", "SGN →", "DLI →", "🍽", "🕌"),
    summary_title="The Six Days",
    summary_head=("Day", "Date", "Where you sleep", "The point of the day", "Outfit"),
    summary_rows=[
        ("Day 1", "Tue, 8 Sep", "Alagon Saigon", "MH750 lands 10:00 — market, post office, boulevard", "Soft blue + brown"),
        ("Day 2", "Wed, 9 Sep", "<b>Fly</b> → La Fleur, Da Lat", "VN1382 10:20, Tà Nung, the lake", "Khaki + black"),
        ("Day 3", "Thu, 10 Sep", "La Fleur, Da Lat", "Cloud bridge at dawn, Cầu Đất, Euro Garden", "Black leather + white"),
        ("Day 4", "Fri, 11 Sep", "La Fleur, Da Lat", "Hydrangeas, Crazy House, Jumu'ah, Pink Valley, Langbiang", "Soft pink + white"),
        ("Day 5", "Sat, 12 Sep", "<b>Drive</b> → The Cliff", "Coaster, Clay Tunnel, Happy Hill, then the pass", "Cream fairytale"),
        ("Day 6", "Sun, 13 Sep", "—", "White dunes at sunrise, MH767 19:25 home", "Blue + yellow"),
    ],
    book_now_head="Confirmed — and the few things still to do",
    book_now=[
        ("✈ Flights — all three booked",
         "<b>MH750</b> KUL 08:55 → SGN 10:00 on the 8th &nbsp;·&nbsp; <b>VN1382</b> SGN 10:20 → Da Lat ~11:10 on the 9th &nbsp;·&nbsp; <b>MH767</b> SGN 19:25 → KUL ~22:15 on the 13th."),
        ("🏨 Hotels — all three booked",
         "<b>Alagon Saigon</b> 8→9 &nbsp;·&nbsp; <b>La Fleur Premium Central</b>, 5–7A Trần Phú, Da Lat 9→12 &nbsp;·&nbsp; <b>The Cliff Resort</b>, Phú Hài, Phan Thiết 12→13. All in 14:00, out 12:00."),
        ("🚗 Driver — arranged",
         "Give him the day pages. The times that matter to him: <b>04.00 on the 10th</b> (cloud bridge), <b>14.15 on the 12th</b> (QL28B before dark), <b>04.45 on the 13th</b> (White Dunes)."),
        ("Still to do — ask La Fleur for a breakfast box",
         "For the 04.15 start on the 10th. Nothing is open that early and there is no halal food at Cầu Đất. While you're there, confirm Cao Nguyên Hoa's opening hours — it's recent and they move."),
        ("Still to do — the dune jeep, and Jumu'ah",
         "The Bàu Trắng jeep is hired at the gate, not through your driver — agree the price, and per person or per vehicle, <b>before</b> getting in. And ask Fatimah about Friday prayer times when you're there for dinner on the 9th."),
        ("Cancel the Bandung side, if it isn't done",
         "Holiday Inn Pasteur, Swiss-Belresort Dago, Fairfield CGK — ask for a waiver citing the airport closure. Message Kiki, and re-issue the insurance for Vietnam."),
    ],
    know_cols=3,
    good_to_know=[
        ("Halal", "Easiest in Saigon — the hotel is by the mosque. Two kitchens in Da Lat, T'HALAL near The Cliff. See the food page."),
        ("Visa", "Visa-free for Malaysians, 30 days. Carry the hotel bookings and the MH767 ticket."),
        ("Three climates", "Saigon 30°C+ and humid; Da Lat 17–24°C, cold before dawn; Phan Thiết 25–31°C and bright."),
        ("Money", "Vietnamese dong. Cash for entry tickets (100–120k a head), the dune jeep and the markets."),
        ("Getting around", "Your driver covers everything out of town. Grab for short hops in Saigon and Da Lat."),
        ("Friday 11 Sept", "Jumu'ah falls on a Da Lat day. The morning stays in town; lunch is at Fatimah, which has a prayer space."),
    ],
    sign=("<b>MH750 ref:</b> ________ &nbsp; <b>VN1382 ref:</b> ________ &nbsp; <b>MH767 ref:</b> ________ &nbsp; "
          "<b>Alagon:</b> ________ &nbsp; <b>La Fleur:</b> ________ &nbsp; <b>The Cliff:</b> ________ &nbsp; "
          "<b>Driver:</b> ________ &nbsp; <i>Schedules checked 6 Sept 2026.</i>"),
    days=DAYS,
    extra_pages=[
        dict(
            color="#B23A16",
            kicker="EAT",
            title="Halal food — every meal on this trip",
            subtitle="Saigon is easy. Da Lat has exactly two. Plan the Cầu Đất day around that.",
            col_heads=("Place", "Where", "What to know"),
            rows=[
                ("Đông Du street", "District 1, Saigon — your hotel's street",
                 "<b>Saigon Central Mosque is here</b>, with a dozen halal restaurants around it. Days 1, 2 and 6 all eat on this street; nothing is more than five minutes from the Alagon."),
                ("Fatimah Restaurant", "18–24 Nguyễn Du, Ward 9, Da Lat",
                 "<b>Halal Vietnamese, with a prayer space.</b> Day 3 dinner and Day 4's Friday lunch — ask them about Jumu'ah when you sit down."),
                ("Halal Food Da Lat", "70 Hoàng Văn Thụ, Ward 5, Da Lat",
                 "<b>Open 07:30–20:30</b>, ~$5–10 a head. Day 3 lunch, Day 4 dinner, Day 5's early lunch. Note the early close — be seated by 19:00."),
                ("T'HALAL Restaurant", "63A Huỳnh Thúc Kháng, Phan Thiết",
                 "<b>Vietnamese halal and seafood, ~10 min from The Cliff.</b> Your hotel's position makes this the default for both coast meals — dinner on the 12th and lunch on the 13th. 100–300k VND."),
                ("Mughal House Indian Halal", "246/2B Nguyễn Đình Chiểu, Mui Ne",
                 "Halal Indian further up the strip, ~15 min from The Cliff. The alternative if you want something other than Vietnamese."),
                ("Vegetarian (chay) restaurants", "Da Lat city — several",
                 "The late-night fallback: Thiền Duyên, Tu Hạnh, Thanh Tịnh, Hoa Sen. No meat at all, so no question about the meat."),
                ("Hotel breakfast", "Alagon · La Fleur · The Cliff",
                 "Eggs, bread, fruit, noodles without the pork broth. <b>Ask La Fleur for a breakfast box for the 10th</b> — you leave at 04.15 and nothing is open."),
                ("Snacks from L'angfarm", "Da Lat city centre",
                 "Packaged dried fruit, nuts, biscuits — buy on the evening of the 9th for the dawn drives on the 10th and 13th."),
            ],
            notes=[
                "<b>Day 3 is the one to plan for.</b> Out east from 04.15 with nothing halal near Cầu Đất — the breakfast box travels with you and lunch waits until noon back in town.",
                "Every café and restaurant from your original Da Lat list stays off the plan, so there is no venue on it where you have to ask about the kitchen.",
                "Saigon has an official city halal restaurant list published by the tourism department if you want more choice than Đông Du.",
            ],
            notes_head="How to eat on this trip",
            foot="halal food",
        ),
        dict(
            color="#15764F",
            kicker="SLEEP",
            title="Your three hotels",
            subtitle="All booked. Check-in 14:00, checkout 12:00 at each.",
            no_maps=True,
            col_heads=("Hotel", "Dates", "Position, and what it means for the day"),
            rows=[
                ("<b>Alagon Saigon Hotel &amp; Spa</b>", "In Tue 8 Sept<br>Out Wed 9 Sept",
                 "District 1, beside <b>Đông Du street — the Saigon Central Mosque is on it</b>, with a dozen halal restaurants around it. Bến Thành, the post office, Nguyễn Huệ and the Café Apartment are all walkable, so Day 1 needs the driver only from the airport. <a href='https://www.google.com/search?q=Alagon+Saigon+Hotel+and+Spa'>Look it up</a>"),
                ("<b>La Fleur Premium Central Apartment</b>", "In Wed 9 Sept<br>Out Sat 12 Sept",
                 "<b>5–7A Trần Phú, Ward 3 — the lake road.</b> Xuan Huong Lake is at the front door, so the Day 2 evening walk costs no travel at all, and Da Lat market is 15 minutes on foot. Apartment-style rooms, and you're here <b>three nights</b>, so unpack once. Every cluster radiates from here: Cầu Đất east, Tà Nung west, Lạc Dương north, Datanla south. <a href='https://www.google.com/search?q=La+Fleur+Premium+Central+Apartment+Da+Lat'>Look it up</a>"),
                ("<b>The Cliff Resort &amp; Residences</b>", "In Sat 12 Sept<br>Out Sun 13 Sept",
                 "<b>5 Nguyễn Đình Chiểu, Phú Hài — the Phan Thiết end of the strip</b>, at the very start of the resort road. That position shapes the last two days: T'HALAL is ~10 minutes away, so both meals are easy; the Red Dunes are ~20–25 minutes up the coast; and the White Dunes are ~60 minutes, which is why the sunrise start is 04.45 and not 05.00. It also shortens the drive back to Saigon. <a href='https://www.google.com/search?q=The+Cliff+Resort+and+Residences+Phan+Thiet'>Look it up</a>"),
            ],
            notes=[
                "All three are booked, so this page is for reference rather than decisions — the times in the day pages already account for where each one sits.",
                "In Da Lat ask for a room off Trần Phú itself: it's the main road round the lake and you are up at 03.45 on the 10th.",
                "At The Cliff, confirm the 04.45 departure with your driver at check-in, and ask the front desk what the Bàu Trắng jeeps are currently charging.",
                "None of the three is halal-certified. Breakfast is easy to navigate; every other meal is on the food page.",
            ],
            notes_head="Notes",
            foot="hotels",
        ),
        dict(
            color="#6D2E5B",
            kicker="CUT",
            title="Removed from your list — and what still didn't fit",
            subtitle="Every café and restaurant is out, as you asked. Everything else on your list is now in the plan.",
            no_maps=True,
            col_heads=("Place", "What it is", "Why it's not in the plan"),
            rows=[
                ("Miền Du Mục · Thác Mây &amp; Chill · Suối Bình Yên · Reply 1994 · Haiyih Coffee",
                 "cafés", "<b>Removed — not halal kitchens.</b> Four were load-bearing, and all four are covered: the Cầu Gỗ bridge replaces Thác Mây at dawn and is better; the Cầu Đất tea hills replace Haiyih on the same hill; the hydrangea fields survive without Suối Bình Yên on their street."),
                ("Giấc Mơ Đà Lạt · Rừng Mơ · Dream Garden · The Forest · The Wilder Nest · Rừng Thông Mơ",
                 "cafés, café-homestays, a bistro", "<b>Removed — not halal kitchens.</b> Dream Garden was the Tà Nung stop; Mongo Land and Cao Nguyên Hoa cover that road on Day 3."),
                ("Da Lat Night Market", "street-food market",
                 "<b>Removed.</b> It is a food market and the grilled stalls are the point of it. L'angfarm, two minutes away, covers the shopping."),
                ("Floating Town · Lạc Hư Cổ Trấn", "ticketed photo parks with a café",
                 "<b>Removed on the same rule</b> — the entry fee is a drink, so they work as cafés. <b>Say the word and both come back</b>: taking the included drink and no food is a defensible line. Floating Town joins Day 3 in Tà Nung; Lạc Hư joins Day 4 coming back from Cầu Đất."),
                ("Pink Valley + Langbiang", "Lạc Dương, 12–22 km north",
                 "<b>Now in — Day 4.</b> Cutting Saigon to one night bought a third Da Lat day, and this is what it went on. They were the one real casualty of every earlier version."),
                ("Auro Garden", "unclear",
                 "Almost certainly <b>Euro Garden Cầu Đất</b>, already on Day 4. If you meant something else, tell me."),
                ("Cầu Gỗ", "wooden bridge",
                 "<b>Already in — Day 4 at dawn.</b> Same place as 'Cầu Đất Cloud Hunting Wooden Bridge' on your list."),
                ("Mekong Delta day trip", "My Tho / Ben Tre, ~2h each way from Saigon",
                 "The alternative Day 2 if you'd rather have countryside than city: floating market, sampans, coconut workshops — and pink water lilies, since this is flood season. <b>Arrange halal food yourself</b>; tour lunches are not."),
            ],
            notes=[
                "Fourteen entries came off the list: twelve cafés and a bistro, the night market, and the two ticketed café-parks.",
                "<b>Every remaining place on your list is now in the plan.</b> Three Da Lat days covers all four compass directions — east, west, north and south — with nothing left over.",
                "If a stop closes or disappoints, pull the nearest swap from this page rather than driving somewhere new.",
            ],
            notes_head="What this cost, honestly",
            foot="removed + spare",
        ),
    ],
)

if __name__ == "__main__":
    engine.write(TRIP,
                 os.path.join(OUT_DIR, "Itinerary-Saigon-DaLat-MuiNe.html"),
                 os.path.join(OUT_DIR, "Itinerary-Saigon-DaLat-MuiNe.pdf"))
