#!/usr/bin/env python3
"""Da Lat (2.5 days) → Mui Ne → home from Saigon. 8-12 September 2026.

Non-halal cafés and restaurants removed from the shortlist entirely, as asked.
Direct AirAsia KUL→Da Lat in, Malaysia Airlines Saigon→KUL home on the 12th.
Hotels named, with check-in and checkout, on the day rows.

Run:    python3 dalat-muine-saigon/build_trip_pdf.py
Output: dalat-muine-saigon/Itinerary-DaLat-MuiNe.html  +  .pdf
"""

import os
import sys

sys.path.insert(0, os.path.join(os.path.dirname(os.path.abspath(__file__)), ".."))
from trips import itinerary_pdf as engine  # noqa: E402

OUT_DIR = os.path.dirname(os.path.abspath(__file__))
GUESTS = "Haris Haikal &amp; Aina Izzaty"
H_DALAT = "Hôtel Colline Dalat (4★)"
H_MUINE = "Bamboo Village Beach Resort &amp; Spa (4★)"

DAYS = [
    dict(
        n="DAY 1", date="Tuesday, 8 September", title="Direct to Da Lat — Tà Nung, then the lake",
        color="#46688C",
        outfit="<b>Soft blue + brown</b> — travel in it, wear it all evening",
        start="~10.00 from KLIA", finish="~21.30", sleep=f"{H_DALAT} — nights 1–2",
        compact=True,
        rows=[
            ("stop", "~10.00", "KUL → DLI — AirAsia AK571, <b>direct</b>", "KLIA", "2h 10m",
             "Straight into Da Lat, no Saigon connection. Departures run 10:00–11:00, landing 11:10–12:10. <b>It flies about 4 days a week — check 8 Sept is one before you book anything else.</b> Vietnam is 1 hour behind."),
            ("move", "Lien Khuong airport &rarr; Da Lat city &mdash; 30 km, ~40 min", "", "", "", ""),
            ("stop", "~13.15", f"Check in — <b>{H_DALAT}</b>",
             "10 Phan Bội Châu, city centre", "45 min",
             "Check-in from 14:00 (they'll usually take you earlier or hold bags). 200 m from Xuan Huong Lake, a few minutes' walk to the night market and to both halal restaurants."),
            ("move", "~35 min southwest to Tà Nung", "", "", "", ""),
            ("stop", "~14.45", "Mongo Land", "Tà Nung commune — 17 km southwest", "1.5h",
             "Mongolian steppe as a theme park: yurts, horse riding, archery, nomad dress-up, rainbow slide. <b>Closes 17:00</b>, so this is the reason to go straight out rather than settle into the room."),
            ("stop", "~16.30", "KDL Sinh Thái Cao Nguyên Hoa", "Tà Nung area", "45 min",
             "Flower-highland eco park, minutes from Mongo Land. Confirm hours with the hotel — it's recent."),
            ("move", "~35 min back into the city", "", "", "", ""),
            ("stop", "~18.15", "Xuan Huong Lake", "City centre — walk from the hotel", "1h",
             "The lake loop at dusk, lit and busy. Straight out of the hotel's front door."),
            ("stop", "~19.30", "🍽 Dinner — <b>Fatimah Restaurant</b> (halal)",
             "18–24 Nguyễn Du, Ward 9", "1.25h",
             "Halal Vietnamese with a prayer space — one of only two halal kitchens in Da Lat. About 10 minutes from the hotel."),
            ("stop", "~21.00", "L'angfarm Center", "City centre", "45 min",
             "Dried fruit, artichoke tea, jam, coffee, macadamia — all packaged. Browse tonight, buy on the last morning so it travels once."),
        ],
        notes=[
            "<b>If the flight lands late, drop Tà Nung</b> and keep the lake and L'angfarm — it's the only cluster on the west side and losing it costs nothing else.",
            "Da Lat is at 1,500 m: 17–24°C, about 17°C tonight. Jacket out tonight and again before dawn tomorrow.",
            "<b>Alarm at 03.45.</b> Tomorrow starts in the dark.",
        ],
    ),
    dict(
        n="DAY 2", date="Wednesday, 9 September", title="Dawn on the cloud bridge, then Cầu Đất",
        color="#A8763A",
        outfit="<b>Black leather + white</b> for the 04.15 start &middot; change into <b>cream fairytale</b> at Euro Garden",
        start="04.15", finish="~20.30", sleep=f"{H_DALAT} — night 2",
        compact=True,
        rows=[
            ("stop", "04.15", "Leave the hotel — take the packed breakfast", "", "—",
             "Ask reception the night before for a breakfast box; you'll be back long after service and out before it starts. Torch, jacket, flask."),
            ("move", "~1 hour east through Trại Mát to Cầu Đất", "", "", "", ""),
            ("stop", "~05.15", "Cầu Gỗ Săn Mây — the cloud-hunting wooden bridge",
             "Cầu Đất tea hills, ~27 km east", "2h",
             "The wooden walkway out over the tea slopes with cloud sitting in the valley beneath it. Past Cầu Đất Farm, turn toward the lavender field, then three minutes on. This is the picture of the trip."),
            ("stop", "~07.30", "Cầu Đất tea hills", "Cầu Đất, QL20", "1h",
             "The terraces are free to walk and at their best in the leftover early cloud. Eat the breakfast box up here."),
            ("stop", "~08.45", "Euro Garden Cầu Đất", "QL20, Cầu Đất — 25 km east", "2.5h",
             "7.2 ha at 1,650 m: seasonal flower fields, a miniature French castle, an Eiffel Tower. Change into the cream outfit here — this is its location."),
            ("move", "DRIVE: back west to the city &mdash; ~45 min", "", "", "", ""),
            ("stop", "~12.15", "🍽 Lunch — <b>Halal Food Da Lat</b>",
             "70 Hoàng Văn Thụ, Ward 5", "1h",
             "Open 07:30–20:30, about $5–10 a head. The second of Da Lat's two halal kitchens."),
            ("stop", "~13.45", "Crazy House (Hằng Nga)", "Huỳnh Thúc Kháng, city", "1.25h",
             "The tree-and-cave house. Narrow stairs and it gets busy — early afternoon is workable, mid-morning is not."),
            ("stop", "~15.15", "Back to the hotel — rest", f"{H_DALAT}", "2.5h",
             "You have been up since 03.45. Take the afternoon off properly; tomorrow is a driving day."),
            ("stop", "~18.00", "🍽 Dinner — <b>Fatimah</b> or <b>Halal Food Da Lat</b>",
             "Nguyễn Du / Hoàng Văn Thụ", "1.5h",
             "If you pick Halal Food Da Lat, be seated by 19:00 — <b>it closes at 20:30</b>."),
            ("stop", "~20.00", "Pack — you change city tomorrow", f"{H_DALAT}", "—", ""),
        ],
        notes=[
            "<b>Food needs planning today.</b> There is nothing halal out at Cầu Đất, so breakfast travels with you and the first real meal is lunch back in town.",
            "The whole morning is one road east and back — no doubling. Book the car the night before with an 04.00 pickup.",
            "Cầu Đất is 1,650 m and cold before sunrise; by noon you'll want the t-shirt.",
        ],
    ),
    dict(
        n="DAY 3", date="Thursday, 10 September", title="Hydrangeas and the coaster, then the pass to the sea",
        color="#D4749B",
        outfit="<b>Soft pink + white</b> — the hydrangea fields are the backdrop",
        start="07.45", finish="~21.00", sleep=f"<b>Move</b> → {H_MUINE} — nights 3–4",
        compact=True,
        rows=[
            ("stop", "07.45", f"Checkout — <b>{H_DALAT}</b>, bags into the car",
             "10 Phan Bội Châu", "20 min",
             "Checkout is 12:00, but you're leaving the city after lunch — settle up now and travel with the bags."),
            ("stop", "~08.15", "Trại Mát hydrangea fields", "Hoa Cẩm Tú Cầu street, Ward 3", "1.25h",
             "Hydrangea Street, and the cẩm tú cầu fields along it. <b>They flower May to December</b>, so they're out now — and morning light is the good light."),
            ("move", "~20 min south on QL20", "", "", "", ""),
            ("stop", "~09.50", "Datanla — new alpine coaster", "QL20, ~5 km south", "1.25h",
             "The rebuilt coaster down through the forest, falls at the bottom. You control the brake — once slow for the video, once fast."),
            ("move", "~15 min", "", "", "", ""),
            ("stop", "~11.20", "Happy Hill", "Đá Tiên, Hoa Phượng Tím st, Ward 4 — 12 km", "1.25h",
             "Film-set park on Tuyen Lam lake: windmills, colour, staged photo corners. Open 07:00–17:30."),
            ("move", "~10 min", "", "", "", ""),
            ("stop", "~12.45", "Đường Hầm Điêu Khắc (Clay Tunnel)", "Tuyen Lam lake", "1h",
             "A sculpted red-clay history of Da Lat — the whole city rebuilt in mud, including the station and Crazy House. Odd, and better than it sounds."),
            ("stop", "~13.50", "🍽 Late lunch — <b>Halal Food Da Lat</b>, then go",
             "70 Hoàng Văn Thụ, Ward 5", "45 min",
             "Last halal meal until Mui Ne. Ten minutes back into town from Tuyen Lam, and it's on the way to the QL28B junction."),
            ("move", "DRIVE: Da Lat &rarr; Mui Ne on QL28B over the Đại Ninh pass &mdash; 155 km, 3.5&ndash;4 hours", "", "", "", ""),
            ("stop", "~18.30", f"Check in — <b>{H_MUINE}</b>",
             "Ham Tien beach strip, Mui Ne", "45 min",
             "Check-in from 14:00, so you're well clear. Beachfront, tropical gardens, big spa — you'll want it tomorrow afternoon."),
            ("stop", "~19.30", "🍽 Dinner — <b>Mughal House Indian Halal</b>",
             "246/2B Nguyễn Đình Chiểu, Mui Ne", "1.5h",
             "Halal Indian on the main strip, minutes from the resort. The reliable dinner in Mui Ne."),
        ],
        notes=[
            "<b>Leave Da Lat by 14.45 at the very latest.</b> QL28B comes down the Đại Ninh pass and you want that in daylight. If the morning slips, drop the Clay Tunnel.",
            "You miss the Red Dunes sunset by leaving after lunch — that's the cost of a full Da Lat morning. Catch them at sunset tomorrow instead if you'd rather.",
            "17°C at breakfast, 31°C at dinner. Jacket to the bottom of the bag after this morning.",
        ],
    ),
    dict(
        n="DAY 4", date="Friday, 11 September", title="Mui Ne — white dunes at sunrise, red canyon after",
        color="#1E7FA8",
        outfit="<b>Blue + yellow</b> — sand, sky and sea all day",
        start="05.00", finish="~21.00", sleep=f"{H_MUINE} — night 4",
        compact=True,
        rows=[
            ("stop", "05.00", "White Sand Dunes (Bàu Trắng) — sunrise",
             "~35 km northeast, ~45 min", "2.5h",
             "The pale dunes, the only real desert in Vietnam. Sunrise is cool, empty, and the whole point. Jeeps and quads wait at the gate — <b>agree the price, and per person or per vehicle, before getting in</b>."),
            ("stop", "~07.45", "Bàu Trắng lotus lake", "Beside the dunes", "45 min",
             "Freshwater lake hard against the sand, fringed with lotus. Water, lotus and desert in one frame."),
            ("move", "~45 min back to Ham Tien", "", "", "", ""),
            ("stop", "~09.30", "🍽 Breakfast at the resort", f"{H_MUINE}", "1h",
             "Included, and the easiest safe meal of the day — eggs, bread, fruit, noodles without the pork broth."),
            ("stop", "~10.45", "Fairy Stream (Suối Tiên)", "Ham Tien, off the main road", "1.25h",
             "Wade barefoot up a warm ankle-deep stream between red and white sandstone. It opens into a small canyon. Shoes stay at the entrance."),
            ("stop", "~13.30", "🍽 Lunch — <b>T'HALAL</b> or <b>Mughal House</b>",
             "63A Huỳnh Thúc Kháng, Phan Thiết / Mui Ne strip", "1.25h",
             "T'HALAL does Vietnamese halal and seafood in town — pairs naturally with going in for prayers. 100–300k VND."),
            ("stop", "~15.00", "Beach and pool — the hot hours", f"{H_MUINE}", "1.5h",
             "This is what the resort is for. Do nothing until four."),
            ("stop", "~16.30", "Fishing village + Ông Địa rock beach", "Mui Ne village end", "1.25h",
             "Round blue coracle boats pulled up on the sand — the most photographed thing here after the dunes. Best when the fleet is in."),
            ("stop", "~18.00", "Red Sand Dunes (Đồi Hồng) for sunset", "~10 min from the strip", "1h",
             "Orange dunes right by the road, at their best in the last hour of light. This is the sunset you gave up yesterday."),
            ("stop", "~19.30", "🍽 Dinner, then pack", "Mui Ne strip", "1.5h", ""),
        ],
        notes=[
            "<b>Today is Friday — Jumu'ah.</b> Ask Bamboo Village at Thursday check-in about the nearest mosque; Bình Thuận has Cham Muslim communities and Phan Thiết is ~20 min down the coast — the same town as T'HALAL, so prayers and lunch pair up.",
            "Two 5am starts in three days, then a deliberately empty afternoon. The dunes only work at the ends of the day, so that's the trade.",
            "Sun is far stronger than Da Lat — hat, sunscreen, water. Sand gets everywhere; leave the good camera bag in the room. <b>Book tomorrow's car tonight</b>: 07.00 pickup for Saigon.",
        ],
    ),
    dict(
        n="DAY 5", date="Saturday, 12 September", title="Down the expressway, fly home from Saigon",
        color="#6B6A52",
        outfit="<b>Khaki + black</b> — travel day",
        start="07.00", finish="KUL", sleep="—",
        rows=[
            ("stop", "07.00", f"Checkout — <b>{H_MUINE}</b>", "Ham Tien", "20 min",
             "Checkout is 12:00 but you want the road early. Ask for breakfast boxed the night before."),
            ("move", "DRIVE: Mui Ne &rarr; Saigon on the Dầu Giây&ndash;Phan Thiết expressway &mdash; 200&ndash;220 km, 2.5&ndash;3 hours", "", "", "", ""),
            ("stop", "~10.15", "Arrive Saigon — District 1", "Ho Chi Minh City", "—",
             "Tan Son Nhat is inside the city, so you are almost at the airport already."),
            ("stop", "~10.45", "🍽 Early lunch — Đông Du street, halal", "District 1, by Bến Thành", "1.25h",
             "Saigon's Muslim quarter: several halal restaurants and a mosque, all walkable. The easiest halal eating of the whole trip — and the last proper meal before the flight."),
            ("stop", "~12.15", "Check-in + immigration", "Tan Son Nhat T2", "2h buffer",
             "International departures, Terminal 2. Saigon traffic is the variable, not the airport."),
            ("stop", "afternoon", "SGN → KUL — Malaysia Airlines", "Tan Son Nhat T2", "~2h",
             "MH750 / MH758 / MH766 — about 7 a day, so pick one <b>after 14:00</b> and the morning drive has real slack. Malaysia is 1 hour ahead."),
        ],
        notes=[
            "<b>Saigon is the nearest useful airport to Mui Ne</b> — 2.5–3h against ~4h north to Cam Ranh, with 7 MAS flights a day to KUL rather than ~4 a week.",
            "Two airlines, two tickets: AirAsia out to Da Lat, MAS home from Saigon. Nothing connects them, so leave the slack the schedule already has.",
            "If the drive worries you, move to Saigon on Friday evening instead and lose the Red Dunes sunset.",
        ],
    ),
]

TRIP = dict(
    doc_title="Da Lat &amp; Mui Ne — 8-12 September 2026",
    kicker="Halal-only meals &middot; your shortlist, cafés removed &middot; Bandung is off (Anak Krakatau)",
    title="Da Lat &rarr; Mui Ne &rarr; Saigon<br>8 &ndash; 12 September 2026",
    subtitle=(f"{GUESTS} &middot; AirAsia direct into Da Lat, Malaysia Airlines home from Saigon<br>"
              "2½ days Da Lat, 1 full day Mui Ne. Every meal is a halal address."),
    travellers=GUESTS,
    country="Vietnam",
    no_map=("Breakfast", "Lunch", "Dinner", "Check in", "Checkout", "Leave the", "Back to the",
            "Beach and pool", "Arrive Saigon", "Pack", "Jumu'ah", "KUL →", "SGN →", "🍽", "🕌"),
    summary_title="The Five Days",
    summary_head=("Day", "Date", "Where you sleep", "The point of the day", "Outfit"),
    summary_rows=[
        ("Day 1", "Tue, 8 Sep", "Hôtel Colline Dalat", "Direct flight in, Tà Nung, the lake", "Soft blue + brown"),
        ("Day 2", "Wed, 9 Sep", "Hôtel Colline Dalat",
         "Cloud bridge at dawn, Cầu Đất, Crazy House", "Black leather am · cream"),
        ("Day 3", "Thu, 10 Sep", "<b>Move</b> → Bamboo Village",
         "Hydrangeas, coaster, Happy Hill, then the pass", "Soft pink + white"),
        ("Day 4", "Fri, 11 Sep", "Bamboo Village, Mui Ne",
         "White dunes at sunrise, Fairy Stream, Red Dunes", "Blue + yellow"),
        ("Day 5", "Sat, 12 Sep", "—", "Expressway to Saigon, halal lunch, MAS home", "Khaki + black"),
    ],
    book_now_head="Book Tonight, In This Order",
    book_now=[
        ("Check AirAsia AK571 flies on 8 September",
         "KUL → Da Lat direct, 2h10, departing 10:00–11:00 — but only ~<b>4 days a week</b>. Everything hangs off this. If the 8th isn't one, fly KUL → Saigon on MAS and connect (55 min, six a day)."),
        ("MAS SGN → KUL on 12 September, after 14:00",
         "MH750 / MH758 / MH766, ~7 a day. Leaves the morning drive real slack."),
        ("<b>Hôtel Colline Dalat</b> — 2 nights, 8–10 Sept",
         "4★, 10 Phan Bội Châu — 200 m from Xuan Huong Lake, walking distance to both halal restaurants. In 14:00, out 12:00."),
        ("<b>Bamboo Village Beach Resort &amp; Spa</b> — 2 nights, 10–12 Sept",
         "4★ beachfront on the Ham Tien strip, gardens and a well-known spa. In 14:00, out 12:00."),
        ("Cars: three bookings",
         "9 Sept <b>04.00 pickup</b>, all day east. 10 Sept Da Lat → Mui Ne on <b>QL28B</b>, ~14.45. 12 Sept Mui Ne → Saigon, 07.00."),
        ("A jeep for the white dunes on the 11th",
         "05.00 start — Bamboo Village arranges it. Agree the price up front."),
        ("Cancel the Bandung side, and ask about Friday prayers",
         "Holiday Inn Pasteur, Swiss-Belresort Dago, Fairfield CGK — ask for a waiver citing the airport closure. Message Kiki, re-issue the insurance. And 11 Sept is a Friday: ask Bamboo Village about the nearest mosque."),
    ],
    know_cols=3,
    good_to_know=[
        ("Halal", "Two halal kitchens in Da Lat, both in the city; two in Mui Ne / Phan Thiết. Every meal on this plan is one of them. Full list on the food page."),
        ("Visa", "Visa-free for Malaysians, 30 days. Carry hotel bookings and onward tickets."),
        ("Three climates", "Da Lat 17–24°C, cold before dawn; Mui Ne 25–31°C; Saigon 30°C+ and humid."),
        ("Money", "Vietnamese dong. Cash for entry tickets (100–120k a head), the dune jeep and markets."),
        ("Getting around", "Grab in Da Lat and Saigon; a booked car for the out-of-town days. Mui Ne is one strip."),
        ("Why 12 Sept works", "Cutting the cafés freed up two half-days. A 13 Sept return would buy Pink Valley and Langbiang — see the spare page."),
    ],
    sign=("<b>AK571 out:</b> _____________ &nbsp; <b>MAS home:</b> _____________ &nbsp; "
          "<b>Colline booking:</b> _____________ &nbsp; <b>Bamboo Village booking:</b> _____________<br>"
          "<b>Driver (Cầu Đất):</b> _____________ &nbsp; <b>Driver (QL28B):</b> _____________ &nbsp; "
          "<b>Driver (Saigon):</b> _____________ &nbsp; <i>Checked 6 Sept 2026.</i>"),
    days=DAYS,
    extra_pages=[
        dict(
            color="#B23A16",
            kicker="EAT",
            title="Halal food — every meal on this trip",
            subtitle="The five addresses the whole plan is built around",
            col_heads=("Place", "Where", "What to know"),
            rows=[
                ("Fatimah Restaurant", "18–24 Nguyễn Du, Ward 9, Da Lat",
                 "<b>Halal Vietnamese, with a prayer space.</b> The better sit-down of the two. Day 1 dinner, and the fallback on Day 2."),
                ("Halal Food Da Lat", "70 Hoàng Văn Thụ, Ward 5, Da Lat",
                 "<b>Open 07:30–20:30</b>, about $5–10 a head. Day 2 lunch and Day 3's late lunch before the pass. Note the early close."),
                ("Mughal House Indian Halal", "246/2B Nguyễn Đình Chiểu, Mui Ne",
                 "<b>Halal Indian on the Ham Tien strip</b>, minutes from Bamboo Village. Day 3 dinner."),
                ("T'HALAL Restaurant", "63A Huỳnh Thúc Kháng, Phan Thiết",
                 "<b>Vietnamese halal and seafood</b>, ~20 min down the coast. Day 4 lunch, and it pairs with going into town for Friday prayers."),
                ("Đông Du street", "District 1, Saigon, by Bến Thành",
                 "Saigon's Muslim quarter — several halal restaurants and a mosque, all walkable. Day 5 lunch before the flight."),
                ("Halal Indian + seafood", "109B Nguyễn Đình Chiểu, Phan Thiết",
                 "Spare Phan Thiết option if T'HALAL is full. Phone +84 934 790 556."),
                ("Vegetarian (chay) restaurants", "Da Lat city — several",
                 "The late-night fallback: Thiền Duyên, Tu Hạnh, Thanh Tịnh, Hoa Sen. No meat at all, so no question about the meat."),
                ("Hotel breakfast", "Colline and Bamboo Village",
                 "Both included. Eggs, bread, fruit, noodles without the pork broth. Ask Colline for a <b>breakfast box on the 9th</b> — you leave at 04.15."),
            ],
            notes=[
                "<b>Day 2 is the one to plan for.</b> Out east from 04.15 with nothing halal anywhere near Cầu Đất — the breakfast box travels with you and lunch waits until you're back in town at 12.15.",
                "Every café and restaurant from your original list has been removed from the plan, so there is no venue on it where you have to ask questions about the kitchen.",
                "Snacks for the two dawn starts: L'angfarm sells packaged dried fruit, nuts and biscuits — stock up on Day 1.",
            ],
            notes_head="How to eat on this trip",
            foot="halal food",
        ),
        dict(
            color="#15764F",
            kicker="SLEEP",
            title="The two hotels",
            subtitle="Both 4★, both chosen for position rather than luxury",
            no_maps=True,
            col_heads=("Hotel", "Dates", "Why this one, and how to book"),
            rows=[
                ("<b>Hôtel Colline Dalat</b> — 4★",
                 "In Tue 8 Sept<br>Out Thu 10 Sept",
                 "10 Phan Bội Châu, city centre. <b>200 m from Xuan Huong Lake</b>, a few minutes' walk to the night market, L'angfarm and both halal restaurants — which matters more here than anywhere, because there are only two of them. Opened 2019, rated ~8.8. Every cluster on your list radiates out from this point: Cầu Đất east, Tà Nung west, Datanla south. Check-in 14:00, checkout 12:00. <a href='https://www.google.com/search?q=Hotel+Colline+Dalat+booking'>Find it &amp; book</a>"),
                ("<i>Alternative:</i> Muong Thanh Holiday Da Lat — 4★",
                 "same dates",
                 "42 Phan Bội Châu, the same street. Also 200 m from the lake, bigger and chain-run, with an indoor pool and spa. Take it if Colline is full or pricier for your dates. <a href='https://www.google.com/search?q=Muong+Thanh+Holiday+Da+Lat+booking'>Find it &amp; book</a>"),
                ("<b>Bamboo Village Beach Resort &amp; Spa</b> — 4★",
                 "In Thu 10 Sept<br>Out Sat 12 Sept",
                 "Ham Tien beach strip, Mui Ne. Beachfront, family-run since 1998, tropical gardens and thatched-roof villas, and one of the best-regarded spas in Mui Ne — which is the point, because Day 4's afternoon is deliberately empty. Minutes from Mughal House, Fairy Stream and the fishing village; the dune jeep collects from the door. Check-in 14:00, checkout 12:00. <a href='https://www.google.com/search?q=Bamboo+Village+Beach+Resort+Mui+Ne+booking'>Find it &amp; book</a>"),
                ("<i>Alternative:</i> The Sailing Bay Beach Resort — 4★",
                 "same dates",
                 "Also on Ham Tien: 2.5 hectares of garden, a big seaside pool, 192 rooms. Larger and more resort-like than Bamboo Village. <a href='https://www.google.com/search?q=Sailing+Bay+Beach+Resort+Mui+Ne+booking'>Find it &amp; book</a>"),
                ("Browse either area", "—",
                 "<a href='https://www.booking.com/landmark/vn/xuan-huong-lake.html'>booking.com — hotels near Xuan Huong Lake</a> &nbsp;·&nbsp; <a href='https://www.booking.com/city/vn/mui-ne.html'>booking.com — all Mui Ne hotels</a>"),
            ],
            notes=[
                "I have not checked live rates or availability for your dates — confirm both before booking the flights around them.",
                "In Da Lat ask for a room off the street: the centre is noisy late and you are up at 03.45 on the 9th.",
                "At Bamboo Village, arrange the dune jeep and the Saigon car <b>at check-in</b> — cheaper than booking either from Malaysia.",
                "Neither hotel is halal-certified. Breakfast is easy to navigate; every other meal is on the food page.",
            ],
            notes_head="Booking notes",
            foot="hotels",
        ),
        dict(
            color="#6D2E5B",
            kicker="CUT",
            title="Removed from your list — and what still didn't fit",
            subtitle="Every café and restaurant is out, as you asked. Here is exactly what went and why.",
            no_maps=True,
            col_heads=("Place", "What it is", "Why it's not in the plan"),
            rows=[
                ("Miền Du Mục · Thác Mây &amp; Chill · Suối Bình Yên · Reply 1994 · Haiyih Coffee",
                 "cafés", "<b>Removed — not halal kitchens.</b> Four of the five were load-bearing: Thác Mây was the old dawn stop (the Cầu Gỗ bridge replaces it, and is better), Haiyih was the Cầu Đất coffee stop, Suối Bình Yên was the hydrangea stop — the fields on that street stay in, on Day 3."),
                ("Giấc Mơ Đà Lạt · Rừng Mơ · Dream Garden · The Forest · The Wilder Nest",
                 "cafés / café-homestays", "<b>Removed — not halal kitchens.</b> Dream Garden was the Tà Nung stop; Mongo Land and Cao Nguyên Hoa cover that road instead on Day 1."),
                ("Rừng Thông Mơ Farm &amp; Bistro", "farm bistro",
                 "<b>Removed — not a halal kitchen.</b>"),
                ("Da Lat Night Market", "street-food market",
                 "<b>Removed.</b> It is a food market and the grilled stalls are the whole point of it. L'angfarm, two minutes away, covers the shopping."),
                ("Floating Town · Lạc Hư Cổ Trấn", "ticketed photo parks with a café",
                 "<b>Removed on the same rule</b> — the entry fee is a drink, so they function as cafés. <b>Say the word and both come back</b>: they're parks you photograph, and taking the included drink and no food is a defensible line. Floating Town would go on Day 1 with Tà Nung; Lạc Hư on Day 2 coming back from Cầu Đất."),
                ("Pink Valley + Langbiang", "flower valley + mountain, Lạc Dương, 12–22 km north",
                 "<b>Not removed — just no day left.</b> They're the only cluster north, and reaching them costs a half-day you don't have with a 12 Sept return. <b>This is what a 13 Sept return buys you</b>: one more Da Lat night, the north cluster on the 11th, Mui Ne on the 12th, home on the 13th."),
                ("Auro Garden", "unclear",
                 "Almost certainly <b>Euro Garden Cầu Đất</b>, which is already on Day 2. If you meant something else, tell me."),
                ("Cầu Gỗ", "wooden bridge",
                 "<b>Already in — Day 2 at dawn.</b> Same place as 'Cầu Đất Cloud Hunting Wooden Bridge' on your list."),
            ],
            notes=[
                "<b>Fourteen places came off the list</b> — twelve cafés and restaurants, plus the night market and the two ticketed café-parks. What's left is fourteen attractions, and twelve of them are in the plan.",
                "The cut cost you less than it looks: the cloud bridge is a better dawn spot than Thác Mây, and the hydrangea fields survive without the café on the same street.",
                "<b>If you want the north cluster, move the return to 13 Sept</b> and I'll rebuild with three Da Lat days.",
            ],
            notes_head="What this cost, honestly",
            foot="removed + spare",
        ),
    ],
)

if __name__ == "__main__":
    engine.write(TRIP,
                 os.path.join(OUT_DIR, "Itinerary-DaLat-MuiNe.html"),
                 os.path.join(OUT_DIR, "Itinerary-DaLat-MuiNe.pdf"))
